### ISSUE TITLE
Todo before launch:

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/WIM-Main-Site#55]
- [x] Compress Images

- [x] Double check styleguide references

- [x] Update featured project info

- [x] Add more static content/design to home page

- [x] Add USGS Footer

- [x] Switch Vue to Production (Gulp build task?)

- [x] Edit site Meta images

- [x] Swap for live Repo.jsons

- [x] Zoom project images

- [x] Crop project screenshots to remove window borders on some

- [x] Home page active link

- [x] Paragraph max width

- [x] Set page title and meta on project pages

- [x] Change to project repos instead of related
